# Generated by Django 2.2.8 on 2020-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=50)),
                ('pub_date_time', models.DateTimeField(verbose_name='date published')),
                ('article_text', models.CharField(max_length=200)),
            ],
        ),
    ]
